# Generated by Django 6.0.3 on 2026-04-01 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('subjects', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la session')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Année académique')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Session d'examen",
                'verbose_name_plural': "Sessions d'examens",
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du type')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('default_duration', models.PositiveIntegerField(default=120, verbose_name='Durée par défaut (minutes)')),
                ('max_score', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Note maximale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Type d'examen",
                'verbose_name_plural': "Types d'examens",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'examen")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('exam_date', models.DateField(verbose_name="Date de l'examen")),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('duration', models.PositiveIntegerField(verbose_name='Durée (minutes)')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note maximale')),
                ('passing_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note de passage')),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('ongoing', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='planned', max_length=20, verbose_name='Statut')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('groups', models.ManyToManyField(to='timetable.groupe', verbose_name='Groupes')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.salle', verbose_name='Salle')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Matière')),
                ('teachers', models.ManyToManyField(to='timetable.enseignant', verbose_name='Surveillants')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examtype', verbose_name="Type d'examen")),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['-exam_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Total étudiants')),
                ('submitted_count', models.PositiveIntegerField(default=0, verbose_name='Copies soumises')),
                ('graded_count', models.PositiveIntegerField(default=0, verbose_name='Copies notées')),
                ('absent_count', models.PositiveIntegerField(default=0, verbose_name='Absents')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne')),
                ('highest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note la plus haute')),
                ('lowest_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note la plus basse')),
                ('success_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de réussite (%)')),
                ('a_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de A')),
                ('b_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de B')),
                ('c_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de C')),
                ('d_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de D')),
                ('e_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de E')),
                ('f_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de F')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': "Statistiques d'examen",
                'verbose_name_plural': "Statistiques d'examens",
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note maximale')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('grade', models.CharField(blank=True, max_length=5, verbose_name='Appréciation (A, B, C, etc.)')),
                ('status', models.CharField(choices=[('absent', 'Absent'), ('submitted', 'Soumis'), ('graded', 'Noté'), ('appealed', 'Contesté')], default='submitted', max_length=20, verbose_name='Statut')),
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name='Admis')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de notation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam', verbose_name='Examen')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Noté par')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': "Résultat d'examen",
                'verbose_name_plural': "Résultats d'examens",
                'ordering': ['-exam__exam_date', 'student__last_name'],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
