# Generated by Django 6.0.3 on 2026-04-01 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departements', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la matière')),
                ('code', models.CharField(choices=[('INF', 'Informatique'), ('MAT', 'Mathématiques'), ('PHY', 'Physique'), ('CHI', 'Chimie'), ('BIO', 'Biologie'), ('FRA', 'Français'), ('ANG', 'Anglais'), ('ESP', 'Espagnol'), ('HIS', 'Histoire'), ('GEO', 'Géographie'), ('ECO', 'Économie'), ('DRT', 'Droit'), ('ART', 'Arts'), ('MUS', 'Musique'), ('EPS', 'Sport'), ('AUT', 'Autre')], max_length=3, verbose_name='Code matière')),
                ('code_unique', models.CharField(max_length=10, unique=True, verbose_name='Code unique')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('credits', models.PositiveIntegerField(default=1, verbose_name='Crédits')),
                ('heures_semaine', models.PositiveIntegerField(default=1, verbose_name='Heures par semaine')),
                ('type_matiere', models.CharField(choices=[('core', 'Matière principale'), ('optional', 'Matière optionnelle'), ('specialization', 'Spécialisation'), ('workshop', 'Atelier')], default='core', max_length=20, verbose_name='Type de matière')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departements.department', verbose_name='Département')),
                ('enseignants', models.ManyToManyField(blank=True, to='timetable.enseignant', verbose_name='Enseignants')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['code_unique', 'nom'],
                'unique_together': {('code', 'departement')},
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_specifiques', models.PositiveIntegerField(blank=True, null=True, verbose_name='Heures spécifiques (si différent)')),
                ('credits_specifiques', models.PositiveIntegerField(blank=True, null=True, verbose_name='Crédits spécifiques (si différent)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enseignant_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.enseignant', verbose_name='Enseignant principal')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.groupe', verbose_name='Groupe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Matière par groupe',
                'verbose_name_plural': 'Matières par groupe',
                'ordering': ['subject', 'groupe'],
                'unique_together': {('subject', 'groupe')},
            },
        ),
        migrations.CreateModel(
            name='SubjectPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_requis', models.CharField(blank=True, max_length=50, verbose_name='Niveau requis')),
                ('description', models.TextField(blank=True, verbose_name='Description du prérequis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_for', to='subjects.subject', verbose_name='Prérequis')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequis_for', to='subjects.subject', verbose_name='Matière requise')),
            ],
            options={
                'verbose_name': 'Prérequis de matière',
                'verbose_name_plural': 'Prérequis de matières',
                'unique_together': {('subject', 'prerequisite')},
            },
        ),
    ]
